FROM node:22-alpine

WORKDIR /app

# Copy main app package files
COPY package*.json ./
COPY prisma ./prisma/

# Install main app dependencies
RUN npm install

RUN npx prisma generate

ENV NODE_ENV=development
ENV PORT=3000

EXPOSE 3000

CMD ["npx", "react-router", "dev"]
