services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_BRANCH: ${BUILD_BRANCH:-local-prod}
        BUILD_COMMIT: ${BUILD_COMMIT:-local}
        BUILD_TIME: ${BUILD_TIME:-unknown}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - DATABASE_URL=${DATABASE_URL}
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
      - MINIO_BUCKET=${MINIO_BUCKET:-grading-files}
      - API_URL=${API_URL}
      - AUTH_KEY=${AUTH_KEY}
      # Gemini API
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: always
    depends_on:
      - redis
      - db
      - minio
    networks:
      - app_network

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      - app_network

  redis:
    image: redis:7.4.1-alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    restart: always
    networks:
      - app_network
  
  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - app_network
  
  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb myminio/${MINIO_BUCKET} --ignore-existing;
      /usr/bin/mc policy set download myminio/${MINIO_BUCKET};
      exit 0;
      "
    networks:
      - app_network

networks:
  app_network:

volumes:
  redis_data:
  postgres_data:
  minio_data: 